/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_vndx_bindings_NativeKt */

#ifndef _Included_dev_vndx_bindings_NativeKt
#define _Included_dev_vndx_bindings_NativeKt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_vndx_bindings_NativeKt
 * Method:    loadFonts
 * Signature: (Ljava/nio/ByteBuffer;I)[Ldev/vndx/bindings/Font;
 */
JNIEXPORT jobjectArray JNICALL Java_dev_vndx_bindings_NativeKt_loadFonts
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     dev_vndx_bindings_NativeKt
 * Method:    destroyFont
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dev_vndx_bindings_NativeKt_destroyFont
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
