/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_vndx_bindings_NativeKt */

#ifndef _Included_dev_vndx_bindings_NativeKt
#define _Included_dev_vndx_bindings_NativeKt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_vndx_bindings_NativeKt
 * Method:    test_jni
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dev_vndx_bindings_NativeKt_test_1jni
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
